# https://docs.haskellstack.org/en/stable/travis_ci/

dist: bionic
language: node_js
node_js:
  - 13
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work
  - $TRAVIS_BUILD_DIR/bot/.stack-work
  - $TRAVIS_BUILD_DIR/server/.stack-work
  - $HOME/client/node_modules

addons:
  apt:
    update: true
    packages:
      - libgmp-dev

env:
  - CI=true NODE_ENV=production
jobs:
  include:
    - stage: Install Frontend dependencies
      script:
        - cd ./client
        - yarn install --frozen-lockfile
        - ls ./node_modules/
    - stage: Audit
      script:
        - cd ./client
        - ls ./node_modules/
        - yarn audit
    - stage: Build Frontend
      script:
        - cd ./client
        - ls ./node_modules/
        - yarn build
    - stage: Test Frontend
      script:
        - cd ./client
        - yarn test --all --ci
    - stage: Install Stack
      script:
        - export DIR=~/.local/bin
        - if [ ! -d "$DIR" ]; then mkdir -p ~/.local/bin; fi
        - export PATH=$HOME/.local/bin:$PATH
        - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
        - stack setup
    - stage: Build dependencies
      script:
        - export PATH=$HOME/.local/bin:$PATH
        - stack build --dependencies-only
    - stage: Build Backend
      script:
        - export PATH=$HOME/.local/bin:$PATH
        - stack build
    - stage: Test Backend
      script:
        - export PATH=$HOME/.local/bin:$PATH
        - stack test
